// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbfzIAE8s7ZsfzeAAA8KR9QQ2Z1llOTVM',
    appId: '1:1034522837150:web:5760b023faa3c1a8f5bb8f',
    messagingSenderId: '1034522837150',
    projectId: 'attendance-system-3976e',
    authDomain: 'attendance-system-3976e.firebaseapp.com',
    storageBucket: 'attendance-system-3976e.firebasestorage.app',
    measurementId: 'G-GHHER1KDBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAej5Vy5qFmF5RRcLCA9HsPq4gnCxxWk7s',
    appId: '1:1034522837150:android:435108055ca6ffc8f5bb8f',
    messagingSenderId: '1034522837150',
    projectId: 'attendance-system-3976e',
    storageBucket: 'attendance-system-3976e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA937KGbkMGbnTe_JJhgCZ_3LvXjqwPJYw',
    appId: '1:1034522837150:ios:ce13c0ddb77c5c33f5bb8f',
    messagingSenderId: '1034522837150',
    projectId: 'attendance-system-3976e',
    storageBucket: 'attendance-system-3976e.firebasestorage.app',
    iosClientId:
        '1034522837150-kvgs2fiabqrem32kkoag054gm5c9j7po.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendanceManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA937KGbkMGbnTe_JJhgCZ_3LvXjqwPJYw',
    appId: '1:1034522837150:ios:ce13c0ddb77c5c33f5bb8f',
    messagingSenderId: '1034522837150',
    projectId: 'attendance-system-3976e',
    storageBucket: 'attendance-system-3976e.firebasestorage.app',
    iosClientId:
        '1034522837150-kvgs2fiabqrem32kkoag054gm5c9j7po.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendanceManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbfzIAE8s7ZsfzeAAA8KR9QQ2Z1llOTVM',
    appId: '1:1034522837150:web:86fd343cdeedaa94f5bb8f',
    messagingSenderId: '1034522837150',
    projectId: 'attendance-system-3976e',
    authDomain: 'attendance-system-3976e.firebaseapp.com',
    storageBucket: 'attendance-system-3976e.firebasestorage.app',
    measurementId: 'G-MPHS8QY98R',
  );
}
